const shortcutData = [
  // GENERAL
  {
    id: 1,
    group: "General",
    shortcut: "Show Command Palette",
    mac: "⌘ + Shift + P, F1",
    windows: "Ctrl + Shift + P, F1",
  },
  {
    id: 2,
    group: "General",
    shortcut: "Quick Open, Go to File...",
    mac: "⌘ + P",
    windows: "Ctrl + P",
  },
  {
    id: 3,
    group: "General",
    shortcut: "New Window/Instance",
    mac: "⌘ + Shift + N",
    windows: "Ctrl + Shift + N",
  },
  {
    id: 4,
    group: "General",
    shortcut: "Close Window/Instance",
    mac: "⌘ + Shift + W",
    windows: "Ctrl + Shift + W",
  },
  {
    id: 5,
    group: "General",
    shortcut: "User Settings",
    mac: "⌘ + ,",
    windows: "Ctrl + ,",
  },
  {
    id: 6,
    group: "General",
    shortcut: "Keyboard Shortcuts",
    mac: "⌘ + K ⌘ + S",
    windows: "Ctrl + K Ctrl + S",
  },
  {
    id: 7,
    group: "General",
    shortcut: "Open File",
    mac: "⌘ + O",
    windows: "Ctrl + O",
  },
  {
    id: 8,
    group: "General",
    shortcut: "Save",
    mac: "⌘ + S",
    windows: "Ctrl + S",
  },
  {
    id: 9,
    group: "General",
    shortcut: "Save As",
    mac: "⌘ + Shift + S",
    windows: "Ctrl + Shift + S",
  },
  {
    id: 10,
    group: "General",
    shortcut: "Close Editor",
    mac: "⌘ + W",
    windows: "Ctrl + W",
  },

  // BASIC EDITING
  {
    id: 11,
    group: "Basic Editing",
    shortcut: "Cut line (empty selection)",
    mac: "⌘ + X",
    windows: "Ctrl + X",
  },
  {
    id: 12,
    group: "Basic Editing",
    shortcut: "Copy line (empty selection)",
    mac: "⌘ + C",
    windows: "Ctrl + C",
  },
  {
    id: 13,
    group: "Basic Editing",
    shortcut: "Move line up/down",
    mac: "⌥ + ↑ / ↓",
    windows: "Alt + ↑ / ↓",
  },
  {
    id: 14,
    group: "Basic Editing",
    shortcut: "Copy line up/down",
    mac: "Shift + ⌥ + ↑ / ↓",
    windows: "Shift + Alt + ↑ / ↓",
  },
  {
    id: 15,
    group: "Basic Editing",
    shortcut: "Delete line",
    mac: "⌘ + Shift + K",
    windows: "Ctrl + Shift + K",
  },
  {
    id: 16,
    group: "Basic Editing",
    shortcut: "Insert line below",
    mac: "⌘ + Enter",
    windows: "Ctrl + Enter",
  },
  {
    id: 17,
    group: "Basic Editing",
    shortcut: "Insert line above",
    mac: "⌘ + Shift + Enter",
    windows: "Ctrl + Shift + Enter",
  },
  {
    id: 18,
    group: "Basic Editing",
    shortcut: "Jump to matching bracket",
    mac: "⌘ + Shift + \\",
    windows: "Ctrl + Shift + \\",
  },
  {
    id: 19,
    group: "Basic Editing",
    shortcut: "Indent line",
    mac: "⌘ + ]",
    windows: "Ctrl + ]",
  },
  {
    id: 20,
    group: "Basic Editing",
    shortcut: "Outdent line",
    mac: "⌘ + [",
    windows: "Ctrl + [",
  },

  // FILE MANAGEMENT
  {
    id: 21,
    group: "File Management",
    shortcut: "New File",
    mac: "⌘ + N",
    windows: "Ctrl + N",
  },
  {
    id: 22,
    group: "File Management",
    shortcut: "Open File...",
    mac: "⌘ + O",
    windows: "Ctrl + O",
  },
  {
    id: 23,
    group: "File Management",
    shortcut: "Save",
    mac: "⌘ + S",
    windows: "Ctrl + S",
  },
  {
    id: 24,
    group: "File Management",
    shortcut: "Save As...",
    mac: "⌘ + Shift + S",
    windows: "Ctrl + Shift + S",
  },
  {
    id: 25,
    group: "File Management",
    shortcut: "Close Editor",
    mac: "⌘ + W",
    windows: "Ctrl + W",
  },
  {
    id: 26,
    group: "File Management",
    shortcut: "Close Folder",
    mac: "⌘ + K F",
    windows: "Ctrl + K F",
  },
  {
    id: 27,
    group: "File Management",
    shortcut: "Reopen closed editor",
    mac: "⌘ + Shift + T",
    windows: "Ctrl + Shift + T",
  },
  {
    id: 28,
    group: "File Management",
    shortcut: "Open next editor",
    mac: "⌘ + PageDown",
    windows: "Ctrl + PageDown",
  },
  {
    id: 29,
    group: "File Management",
    shortcut: "Open previous editor",
    mac: "⌘ + PageUp",
    windows: "Ctrl + PageUp",
  },
  {
    id: 30,
    group: "File Management",
    shortcut: "Open recent file",
    mac: "⌘ + R",
    windows: "Ctrl + R",
  },

  // SEARCH AND REPLACE
  {
    id: 31,
    group: "Search and Replace",
    shortcut: "Find",
    mac: "⌘ + F",
    windows: "Ctrl + F",
  },
  {
    id: 32,
    group: "Search and Replace",
    shortcut: "Replace",
    mac: "⌘ + Option + F",
    windows: "Ctrl + H",
  },
  {
    id: 33,
    group: "Search and Replace",
    shortcut: "Find next",
    mac: "⌘ + G",
    windows: "F3 / Ctrl + F3",
  },
  {
    id: 34,
    group: "Search and Replace",
    shortcut: "Find previous",
    mac: "⌘ + Shift + G",
    windows: "Shift + F3 / Ctrl + Shift + F3",
  },
  {
    id: 35,
    group: "Search and Replace",
    shortcut: "Select all occurrences of Find match",
    mac: "⌘ + Ctrl + G",
    windows: "Ctrl + Alt + Enter",
  },
  {
    id: 36,
    group: "Search and Replace",
    shortcut: "Add selection to next Find match",
    mac: "⌘ + D",
    windows: "Ctrl + D",
  },
  {
    id: 37,
    group: "Search and Replace",
    shortcut: "Move last selection to next Find match",
    mac: "⌘ + Shift + D",
    windows: "Ctrl + Shift + D",
  },
  {
    id: 38,
    group: "Search and Replace",
    shortcut: "Find in files",
    mac: "⌘ + Shift + F",
    windows: "Ctrl + Shift + F",
  },
  {
    id: 39,
    group: "Search and Replace",
    shortcut: "Replace in files",
    mac: "⌘ + Shift + H",
    windows: "Ctrl + Shift + H",
  },

  // INTEGRATED TERMINAL
  {
    id: 40,
    group: "Integrated Terminal",
    shortcut: "Show integrated terminal",
    mac: "⌃ + `",
    windows: "Ctrl + `",
  },
  {
    id: 41,
    group: "Integrated Terminal",
    shortcut: "Create new terminal",
    mac: "⌃ + Shift + `",
    windows: "Ctrl + Shift + `",
  },
  {
    id: 42,
    group: "Integrated Terminal",
    shortcut: "Copy selection",
    mac: "⌘ + C",
    windows: "Ctrl + C",
  },
  {
    id: 43,
    group: "Integrated Terminal",
    shortcut: "Paste into active terminal",
    mac: "⌘ + V",
    windows: "Ctrl + V",
  },
  {
    id: 44,
    group: "Integrated Terminal",
    shortcut: "Scroll up",
    mac: "Shift + PageUp",
    windows: "Shift + PageUp",
  },
  {
    id: 45,
    group: "Integrated Terminal",
    shortcut: "Scroll down",
    mac: "Shift + PageDown",
    windows: "Shift + PageDown",
  },
  {
    id: 46,
    group: "Integrated Terminal",
    shortcut: "Clear terminal",
    mac: "⌘ + K",
    windows: "Ctrl + K",
  },
  {
    id: 47,
    group: "Integrated Terminal",
    shortcut: "Kill the active terminal instance",
    mac: "⌘ + Shift + W",
    windows: "Ctrl + Shift + W",
  },
  {
    id: 48,
    group: "Integrated Terminal",
    shortcut: "Switch terminal",
    mac: "⌃ + Tab",
    windows: "Ctrl + Tab",
  },
  {
    id: 49,
    group: "Integrated Terminal",
    shortcut: "Rename terminal",
    mac: "⌘ + Shift + R",
    windows: "Ctrl + Shift + R",
  },

  // EDITOR MANAGEMENT
  {
    id: 50,
    group: "Editor Management",
    shortcut: "Split editor",
    mac: "⌘ + \\",
    windows: "Ctrl + \\",
  },
  {
    id: 51,
    group: "Editor Management",
    shortcut: "Switch between editors",
    mac: "⌘ + 1 / 2 / 3",
    windows: "Ctrl + 1 / 2 / 3",
  },
  {
    id: 52,
    group: "Editor Management",
    shortcut: "Open editor to the side",
    mac: "⌘ + Enter",
    windows: "Ctrl + Enter",
  },
  {
    id: 53,
    group: "Editor Management",
    shortcut: "Close active editor",
    mac: "⌘ + W",
    windows: "Ctrl + W",
  },
  {
    id: 54,
    group: "Editor Management",
    shortcut: "Close other editors",
    mac: "⌘ + Option + T",
    windows: "Ctrl + Alt + T",
  },
  {
    id: 55,
    group: "Editor Management",
    shortcut: "Move editor into next group",
    mac: "⌘ + Ctrl + →",
    windows: "Ctrl + Alt + →",
  },
  {
    id: 56,
    group: "Editor Management",
    shortcut: "Move editor into previous group",
    mac: "⌘ + Ctrl + ←",
    windows: "Ctrl + Alt + ←",
  },
  {
    id: 57,
    group: "Editor Management",
    shortcut: "Move active editor group",
    mac: "⌘ + K ←/→",
    windows: "Ctrl + K ←/→",
  },
  {
    id: 58,
    group: "Editor Management",
    shortcut: "Focus on editor group",
    mac: "⌘ + 1 / 2 / 3 / 4",
    windows: "Ctrl + 1 / 2 / 3 / 4",
  },
  {
    id: 59,
    group: "Editor Management",
    shortcut: "Toggle editor group sizes",
    mac: "⌘ + K ⌘ + =",
    windows: "Ctrl + K Ctrl + =",
  },
];

export default shortcutData;
